import Head from 'next/head';
import styles from '@/styles/components/Home.module.scss';
import Link from 'next/link';
import Hero from '@/components/modules/Hero';
import Intro from '@/components/modules/Intro';

export default function Home() {
  return (
    <>
      <Head>
        <title>Aimee Non-Profit - Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <main className={styles._}>
        <Intro />
        <p>
          <Link href={'/about'}>Heres More About Us</Link>
        </p>
      </main>
    </>
  );
}
