import Head from 'next/head';
import styles from '@/styles/components/Home.module.scss';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Aimee Non-Profit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles._}>
        <h1>This is the Homepage Content</h1>
        <p>
          Some body <Link href="http://google.com">Google</Link> (so the title
          doesn't get lonely). Lorem ipsum dolor sit amet, consectetur
          adipisicing elit. Blanditiis suscipit odit iure nihil est eius veniam
          possimus <Link href="http://google.com">Google</Link> dignissimos
          molestias quasi aut, similique, natus deleniti recusandae aspernatur
          nobis accusantium quo?
        </p>
        <p>
          <Link href={'/about'}>Heres More About Us</Link>
        </p>
      </main>
    </>
  );
}
